sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: a1988121188
  alioss:
    access-key-secret: u7BEOASfA9lE2q1sVqS1AO2bAcSrel
    access-key-id: LTAI5tPwwjLsvZ8bjXm3U4uC
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: web-sky11
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10